In [1]:
import pandas as pd
from pathlib import Path

In [2]:
base_dir = Path("../data/imdb")

In [3]:
basics = pd.read_csv(base_dir/"title.basics.tsv",sep="\t",low_memory=False)
print("Origibal basicis shape:",basics.shape)
basics.head()

Origibal basicis shape: (12293734, 9)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [4]:
movies = basics[basics["titleType"] == "movie"]
print("Movies only shape:",movies.shape)

Movies only shape: (738068, 9)

In [6]:
movies = movies[["tconst","primaryTitle","originalTitle","startYear","runtimeMinutes","genres","isAdult"]]

In [7]:
movies.isnull().sum()

tconst            0
primaryTitle      3
originalTitle     3
startYear         0
runtimeMinutes    0
genres            0
isAdult           0
dtype: int64

In [9]:
movies = movies.replace("\\N",pd.NA)

In [14]:
movies = movies.dropna(subset=["tconst","primaryTitle","startYear"])

In [15]:
movies["startYear"] = pd.to_numeric(movies["startYear"],errors="coerce")
movies["runtimeMinutes"] = pd.to_numeric(movies["runtimeMinutes"],errors="coerce")

In [16]:
print("Final movies shape:",movies.shape)
movies.head()

Final movies shape: (627592, 7)

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,isAdult
8,tt0000009,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0
144,tt0000147,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,1897.0,100.0,"Documentary,News,Sport",0
498,tt0000502,Bohemios,Bohemios,1905.0,100.0,<NA>,0
570,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906.0,70.0,"Action,Adventure,Biography",0
587,tt0000591,The Prodigal Son,L'enfant prodigue,1907.0,90.0,Drama,0

In [17]:
movies.isnull().sum()

tconst                 0
primaryTitle           0
originalTitle          0
startYear              0
runtimeMinutes    170241
genres             70737
isAdult                0
dtype: int64

In [20]:
output_dir =Path("../data/processed")
output_dir.mkdir(exist_ok=True)

movies.to_csv(
    output_dir / "imdb_movies.csv",
    index=False
)

print("imdb_movies dataset saved.")

imdb_movies dataset saved.

* BUILD IMDB ACTORS DATASET

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
base_dir = Path("../data/imdb")

In [3]:
names = pd.read_csv(base_dir/"name.basics.tsv",sep="\t",low_memory=False)
print("Original names shape:",names.shape)
names.head()

Original names shape: (15092471, 6)

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,1924,2014,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0117057"
2,nm0000003,Brigitte Bardot,1934,2025,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"

In [4]:
names = names.replace("\\N",pd.NA)

In [5]:
names.isnull().sum()

nconst                      0
primaryName                77
birthYear            14426364
deathYear            14837462
primaryProfession     3023128
knownForTitles        1789222
dtype: int64

In [6]:
actors = names[["nconst","primaryName","birthYear","deathYear","primaryProfession","knownForTitles"]]

In [7]:
actors = actors.rename(columns={"primaryName":"actor_name"})

In [8]:
actors["birthYear"] = pd.to_numeric(actors["birthYear"],errors="coerce")
actors["deathYear"] = pd.to_numeric(actors["deathYear"],errors="coerce")

In [9]:
actors.shape

(15092471, 6)

In [10]:
output_dir = Path("../data/processed")
actors.to_csv(
    output_dir / "imdb_actors.csv",
    index=False
)

print("imdb_actors dataset saved.")

imdb_actors dataset saved.

In [11]:
principals = pd.read_csv(base_dir / "title.principals.tsv",sep="\t",low_memory=False)
print("Orginal Prinvipals shape:",principals.shape)
principals.head()

Orginal Prinvipals shape: (97836504, 6)

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0005690,producer,producer,\N
3,tt0000001,4,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1,nm0721526,director,\N,\N

In [12]:
principals = principals.replace("\\N",pd.NA)

In [14]:
actor_movie_map = principals[["tconst","nconst","ordering","category","job","characters"]]

In [15]:
actor_movie_map["ordering"] = pd.to_numeric(actor_movie_map["ordering"],errors="coerce")

In [16]:
print("Actor-Movie map shape:",actor_movie_map.shape)

actor_movie_map.head()

Actor-Movie map shape: (97836504, 6)

,tconst,nconst,ordering,category,job,characters
0,tt0000001,nm1588970,1,self,<NA>,"[""Self""]"
1,tt0000001,nm0005690,2,director,<NA>,<NA>
2,tt0000001,nm0005690,3,producer,producer,<NA>
3,tt0000001,nm0374658,4,cinematographer,director of photography,<NA>
4,tt0000002,nm0721526,1,director,<NA>,<NA>

In [17]:
actor_movie_map.to_csv(
    output_dir / "imdb_actor_movie_map.csv",
    index = False
)

print("imdb_actor_movie_map dataset saved.")

imdb_actor_movie_map dataset saved.

In [18]:
ratings = pd.read_csv(
    base_dir / "title.ratings.tsv",
    sep="\t",
    low_memory=False
)

print("Original rating shape:",ratings.shape)
ratings.head()

Original rating shape: (1635941, 3)

      tconst  averageRating  numVotes
0  tt0000001            5.7      2192
1  tt0000002            5.5       309
2  tt0000003            6.5      2296
3  tt0000004            5.1       196
4  tt0000005            6.2      3028

In [19]:
ratings = ratings.replace("\\N",pd.NA)

In [21]:
movie_ratings = ratings[
    [
        "tconst",
        "averageRating",
        "numVotes"
    ]
]

In [22]:
movie_ratings["avaerageRating"] = pd.to_numeric(movie_ratings["averageRating"],errors = "coerce")
movie_ratings["numVotes"] = pd.to_numeric(movie_ratings["numVotes"],errors="coerce")

In [23]:
print("Movie rating shape:",movie_ratings.shape)
movie_ratings.head()

Movie rating shape: (1635941, 4)

      tconst  averageRating  numVotes  avaerageRating
0  tt0000001            5.7      2192             5.7
1  tt0000002            5.5       309             5.5
2  tt0000003            6.5      2296             6.5
3  tt0000004            5.1       196             5.1
4  tt0000005            6.2      3028             6.2

In [24]:
movie_ratings.to_csv(
    output_dir / "imdb_movie_ratings.csv",
    index=False
)

print("imdb_movie_ratings dataset saved.")

imdb_movie_ratings dataset saved.

* Loading all entity Datasets

In [26]:
movies = pd.read_csv(output_dir / "imdb_movies.csv")
actors = pd.read_csv(output_dir / "imdb_actors.csv")
actor_movie_map = pd.read_csv(output_dir / "imdb_actor_movie_map.csv")
movie_ratings = pd.read_csv(output_dir / "imdb_movie_ratings.csv")

print("Movie:",movies.shape)
print("Actors:",actors.shape)
print("Actor-Movie Map:",actor_movie_map.shape)
print("Rating:",movie_ratings.shape)

Movie: (627592, 7)
Actors: (15092471, 6)
Actor-Movie Map: (97836504, 6)
Rating: (1635941, 4)

In [27]:
master = actor_movie_map.merge(
    movies,
    on = "tconst",
    how = "inner"
)
print("After merging movies:",master.shape)

After merging movies: (7914605, 12)

In [28]:
master.head()

,tconst,nconst,ordering,category,job,characters,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,isAdult
0,tt0000009,nm0063086,1,actress,NaN,"[""Miss Geraldine Holbrook (Miss Jerry)""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0
1,tt0000009,nm0183823,2,actor,NaN,"[""Mr. Hamilton""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0
2,tt0000009,nm1309758,3,actor,NaN,"[""Chauncey Depew - the Director of the New Yor...",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0
3,tt0000009,nm0085156,4,director,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0
4,tt0000009,nm0085156,5,writer,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0

In [29]:
master = master.merge(
    actors,
    on="nconst",
    how="inner"
)

print("After merging actors:",master.shape)

After merging actors: (7914270, 17)

In [30]:
master.head()

,tconst,nconst,ordering,category,job,characters,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,isAdult,actor_name,birthYear,deathYear,primaryProfession,knownForTitles
0,tt0000009,nm0063086,1,actress,NaN,"[""Miss Geraldine Holbrook (Miss Jerry)""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Blanche Bayliss,1878.0,1951.0,actress,tt0000009
1,tt0000009,nm0183823,2,actor,NaN,"[""Mr. Hamilton""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,William Courtenay,1875.0,1933.0,actor,"tt0000009,tt0020355,tt0021535,tt0020403"
2,tt0000009,nm1309758,3,actor,NaN,"[""Chauncey Depew - the Director of the New Yor...",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Chauncey Depew,1834.0,1928.0,"actor,writer","tt0000009,tt0490842,tt1076833,tt4484306"
3,tt0000009,nm0085156,4,director,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Alexander Black,1859.0,1940.0,"director,writer,cinematographer",tt0000009
4,tt0000009,nm0085156,5,writer,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Alexander Black,1859.0,1940.0,"director,writer,cinematographer",tt0000009

In [31]:
master = master.merge(
    movie_ratings,
    on = "tconst",
    how = "left"
)

print("After merging ratings:",master.shape)

After merging ratings: (7914270, 20)

In [32]:
master.head()

,tconst,nconst,ordering,category,job,characters,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,isAdult,actor_name,birthYear,deathYear,primaryProfession,knownForTitles,averageRating,numVotes,avaerageRating
0,tt0000009,nm0063086,1,actress,NaN,"[""Miss Geraldine Holbrook (Miss Jerry)""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Blanche Bayliss,1878.0,1951.0,actress,tt0000009,5.3,234.0,5.3
1,tt0000009,nm0183823,2,actor,NaN,"[""Mr. Hamilton""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,William Courtenay,1875.0,1933.0,actor,"tt0000009,tt0020355,tt0021535,tt0020403",5.3,234.0,5.3
2,tt0000009,nm1309758,3,actor,NaN,"[""Chauncey Depew - the Director of the New Yor...",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Chauncey Depew,1834.0,1928.0,"actor,writer","tt0000009,tt0490842,tt1076833,tt4484306",5.3,234.0,5.3
3,tt0000009,nm0085156,4,director,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Alexander Black,1859.0,1940.0,"director,writer,cinematographer",tt0000009,5.3,234.0,5.3
4,tt0000009,nm0085156,5,writer,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Alexander Black,1859.0,1940.0,"director,writer,cinematographer",tt0000009,5.3,234.0,5.3

In [33]:
master.to_csv(
    output_dir / "imdb_movie_actor_master.csv",
    index=False
    
)
print("Master dataset saved.")

Master dataset saved.

In [34]:
master.shape

(7914270, 20)