In [1]:
import pandas as pd
from pathlib import Path

In [2]:
base_dir = Path("../data/imdb")

In [3]:
basics = pd.read_csv(base_dir/"title.basics.tsv",sep="\t",low_memory=False)
print("Origibal basicis shape:",basics.shape)
basics.head()

Origibal basicis shape: (12293734, 9)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [4]:
movies = basics[basics["titleType"] == "movie"]
print("Movies only shape:",movies.shape)

Movies only shape: (738068, 9)

In [6]:
movies = movies[["tconst","primaryTitle","originalTitle","startYear","runtimeMinutes","genres","isAdult"]]

In [7]:
movies.isnull().sum()

tconst            0
primaryTitle      3
originalTitle     3
startYear         0
runtimeMinutes    0
genres            0
isAdult           0
dtype: int64

In [9]:
movies = movies.replace("\\N",pd.NA)

In [14]:
movies = movies.dropna(subset=["tconst","primaryTitle","startYear"])

In [15]:
movies["startYear"] = pd.to_numeric(movies["startYear"],errors="coerce")
movies["runtimeMinutes"] = pd.to_numeric(movies["runtimeMinutes"],errors="coerce")

In [16]:
print("Final movies shape:",movies.shape)
movies.head()

Final movies shape: (627592, 7)

,tconst,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,isAdult
8,tt0000009,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0
144,tt0000147,The Corbett-Fitzsimmons Fight,The Corbett-Fitzsimmons Fight,1897.0,100.0,"Documentary,News,Sport",0
498,tt0000502,Bohemios,Bohemios,1905.0,100.0,<NA>,0
570,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906.0,70.0,"Action,Adventure,Biography",0
587,tt0000591,The Prodigal Son,L'enfant prodigue,1907.0,90.0,Drama,0

In [17]:
movies.isnull().sum()

tconst                 0
primaryTitle           0
originalTitle          0
startYear              0
runtimeMinutes    170241
genres             70737
isAdult                0
dtype: int64

In [20]:
output_dir =Path("../data/processed")
output_dir.mkdir(exist_ok=True)

movies.to_csv(
    output_dir / "imdb_movies.csv",
    index=False
)

print("imdb_movies dataset saved.")

imdb_movies dataset saved.

* BUILD IMDB ACTORS DATASET

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
base_dir = Path("../data/imdb")

In [3]:
names = pd.read_csv(base_dir/"name.basics.tsv",sep="\t",low_memory=False)
print("Original names shape:",names.shape)
names.head()

Original names shape: (15092471, 6)

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,1924,2014,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0117057"
2,nm0000003,Brigitte Bardot,1934,2025,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"

In [4]:
names = names.replace("\\N",pd.NA)

In [5]:
names.isnull().sum()

nconst                      0
primaryName                77
birthYear            14426364
deathYear            14837462
primaryProfession     3023128
knownForTitles        1789222
dtype: int64

In [6]:
actors = names[["nconst","primaryName","birthYear","deathYear","primaryProfession","knownForTitles"]]

In [7]:
actors = actors.rename(columns={"primaryName":"actor_name"})

In [8]:
actors["birthYear"] = pd.to_numeric(actors["birthYear"],errors="coerce")
actors["deathYear"] = pd.to_numeric(actors["deathYear"],errors="coerce")

In [9]:
actors.shape

(15092471, 6)

In [10]:
output_dir = Path("../data/processed")
actors.to_csv(
    output_dir / "imdb_actors.csv",
    index=False
)

print("imdb_actors dataset saved.")

imdb_actors dataset saved.

In [11]:
principals = pd.read_csv(base_dir / "title.principals.tsv",sep="\t",low_memory=False)
print("Orginal Prinvipals shape:",principals.shape)
principals.head()

Orginal Prinvipals shape: (97836504, 6)

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2,nm0005690,director,\N,\N
2,tt0000001,3,nm0005690,producer,producer,\N
3,tt0000001,4,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1,nm0721526,director,\N,\N

In [12]:
principals = principals.replace("\\N",pd.NA)

In [14]:
actor_movie_map = principals[["tconst","nconst","ordering","category","job","characters"]]

In [15]:
actor_movie_map["ordering"] = pd.to_numeric(actor_movie_map["ordering"],errors="coerce")

In [16]:
print("Actor-Movie map shape:",actor_movie_map.shape)

actor_movie_map.head()

Actor-Movie map shape: (97836504, 6)

,tconst,nconst,ordering,category,job,characters
0,tt0000001,nm1588970,1,self,<NA>,"[""Self""]"
1,tt0000001,nm0005690,2,director,<NA>,<NA>
2,tt0000001,nm0005690,3,producer,producer,<NA>
3,tt0000001,nm0374658,4,cinematographer,director of photography,<NA>
4,tt0000002,nm0721526,1,director,<NA>,<NA>

In [17]:
actor_movie_map.to_csv(
    output_dir / "imdb_actor_movie_map.csv",
    index = False
)

print("imdb_actor_movie_map dataset saved.")

imdb_actor_movie_map dataset saved.

In [18]:
ratings = pd.read_csv(
    base_dir / "title.ratings.tsv",
    sep="\t",
    low_memory=False
)

print("Original rating shape:",ratings.shape)
ratings.head()

Original rating shape: (1635941, 3)

      tconst  averageRating  numVotes
0  tt0000001            5.7      2192
1  tt0000002            5.5       309
2  tt0000003            6.5      2296
3  tt0000004            5.1       196
4  tt0000005            6.2      3028

In [19]:
ratings = ratings.replace("\\N",pd.NA)

In [21]:
movie_ratings = ratings[
    [
        "tconst",
        "averageRating",
        "numVotes"
    ]
]

In [22]:
movie_ratings["avaerageRating"] = pd.to_numeric(movie_ratings["averageRating"],errors = "coerce")
movie_ratings["numVotes"] = pd.to_numeric(movie_ratings["numVotes"],errors="coerce")

In [23]:
print("Movie rating shape:",movie_ratings.shape)
movie_ratings.head()

Movie rating shape: (1635941, 4)

      tconst  averageRating  numVotes  avaerageRating
0  tt0000001            5.7      2192             5.7
1  tt0000002            5.5       309             5.5
2  tt0000003            6.5      2296             6.5
3  tt0000004            5.1       196             5.1
4  tt0000005            6.2      3028             6.2

In [24]:
movie_ratings.to_csv(
    output_dir / "imdb_movie_ratings.csv",
    index=False
)

print("imdb_movie_ratings dataset saved.")

imdb_movie_ratings dataset saved.

* Loading all entity Datasets

In [26]:
movies = pd.read_csv(output_dir / "imdb_movies.csv")
actors = pd.read_csv(output_dir / "imdb_actors.csv")
actor_movie_map = pd.read_csv(output_dir / "imdb_actor_movie_map.csv")
movie_ratings = pd.read_csv(output_dir / "imdb_movie_ratings.csv")

print("Movie:",movies.shape)
print("Actors:",actors.shape)
print("Actor-Movie Map:",actor_movie_map.shape)
print("Rating:",movie_ratings.shape)

Movie: (627592, 7)
Actors: (15092471, 6)
Actor-Movie Map: (97836504, 6)
Rating: (1635941, 4)

In [27]:
master = actor_movie_map.merge(
    movies,
    on = "tconst",
    how = "inner"
)
print("After merging movies:",master.shape)

After merging movies: (7914605, 12)

In [28]:
master.head()

,tconst,nconst,ordering,category,job,characters,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,isAdult
0,tt0000009,nm0063086,1,actress,NaN,"[""Miss Geraldine Holbrook (Miss Jerry)""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0
1,tt0000009,nm0183823,2,actor,NaN,"[""Mr. Hamilton""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0
2,tt0000009,nm1309758,3,actor,NaN,"[""Chauncey Depew - the Director of the New Yor...",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0
3,tt0000009,nm0085156,4,director,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0
4,tt0000009,nm0085156,5,writer,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0

In [29]:
master = master.merge(
    actors,
    on="nconst",
    how="inner"
)

print("After merging actors:",master.shape)

After merging actors: (7914270, 17)

In [30]:
master.head()

,tconst,nconst,ordering,category,job,characters,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,isAdult,actor_name,birthYear,deathYear,primaryProfession,knownForTitles
0,tt0000009,nm0063086,1,actress,NaN,"[""Miss Geraldine Holbrook (Miss Jerry)""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Blanche Bayliss,1878.0,1951.0,actress,tt0000009
1,tt0000009,nm0183823,2,actor,NaN,"[""Mr. Hamilton""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,William Courtenay,1875.0,1933.0,actor,"tt0000009,tt0020355,tt0021535,tt0020403"
2,tt0000009,nm1309758,3,actor,NaN,"[""Chauncey Depew - the Director of the New Yor...",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Chauncey Depew,1834.0,1928.0,"actor,writer","tt0000009,tt0490842,tt1076833,tt4484306"
3,tt0000009,nm0085156,4,director,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Alexander Black,1859.0,1940.0,"director,writer,cinematographer",tt0000009
4,tt0000009,nm0085156,5,writer,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Alexander Black,1859.0,1940.0,"director,writer,cinematographer",tt0000009

In [31]:
master = master.merge(
    movie_ratings,
    on = "tconst",
    how = "left"
)

print("After merging ratings:",master.shape)

After merging ratings: (7914270, 20)

In [32]:
master.head()

,tconst,nconst,ordering,category,job,characters,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,isAdult,actor_name,birthYear,deathYear,primaryProfession,knownForTitles,averageRating,numVotes,avaerageRating
0,tt0000009,nm0063086,1,actress,NaN,"[""Miss Geraldine Holbrook (Miss Jerry)""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Blanche Bayliss,1878.0,1951.0,actress,tt0000009,5.3,234.0,5.3
1,tt0000009,nm0183823,2,actor,NaN,"[""Mr. Hamilton""]",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,William Courtenay,1875.0,1933.0,actor,"tt0000009,tt0020355,tt0021535,tt0020403",5.3,234.0,5.3
2,tt0000009,nm1309758,3,actor,NaN,"[""Chauncey Depew - the Director of the New Yor...",Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Chauncey Depew,1834.0,1928.0,"actor,writer","tt0000009,tt0490842,tt1076833,tt4484306",5.3,234.0,5.3
3,tt0000009,nm0085156,4,director,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Alexander Black,1859.0,1940.0,"director,writer,cinematographer",tt0000009,5.3,234.0,5.3
4,tt0000009,nm0085156,5,writer,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,Romance,0,Alexander Black,1859.0,1940.0,"director,writer,cinematographer",tt0000009,5.3,234.0,5.3

In [33]:
master.to_csv(
    output_dir / "imdb_movie_actor_master.csv",
    index=False
    
)
print("Master dataset saved.")

Master dataset saved.

In [34]:
master.shape

(7914270, 20)

In [35]:
ml_movies = pd.read_csv("../data/ml-latest/movies.csv")
ml_ratings = pd.read_csv("../data/ml-latest/ratings.csv")

print("MovieLens movies:",ml_movies.shape)
print("MovieLens ratings:",ml_ratings.shape)
ml_movies.head()

MovieLens movies: (86537, 3)
MovieLens ratings: (33832162, 4)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [36]:
ml_movies["startYear"] = ml_movies["title"].str.extract(r"\((\d{4})\)")
ml_movies["startYear"] = pd.to_numeric(ml_movies["startYear"],errors="coerce")

In [38]:
ml_movies["primaryTitle"] = ml_movies["title"].str.replace(r"\(\d{4}\)", "",regex=True)
ml_movies["primaryTitle"] = ml_movies["primaryTitle"].str.strip()

In [40]:
ml_engagement = ml_ratings.groupby("movieId").agg(
    watch_count=("userId","count"),
    avg_user_rating=("rating","mean")
).reset_index()
ml_engagement.head()

   movieId  watch_count  avg_user_rating
0        1        76813         3.893508
1        2        30209         3.278179
2        3        15820         3.171271
3        4         3028         2.868395
4        5        15801         3.076957

In [41]:
ml_movies = ml_movies.merge(
    ml_engagement,
    on="movieId",
    how="left"
)

ml_movies.head()

,movieId,title,genres,startYear,primaryTitle,watch_count,avg_user_rating
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995.0,Toy Story,76813.0,3.893508
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995.0,Jumanji,30209.0,3.278179
2,3,Grumpier Old Men (1995),Comedy|Romance,1995.0,Grumpier Old Men,15820.0,3.171271
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995.0,Waiting to Exhale,3028.0,2.868395
4,5,Father of the Bride Part II (1995),Comedy,1995.0,Father of the Bride Part II,15801.0,3.076957

In [42]:
ml_movies.shape

(86537, 7)

In [43]:
master = pd.read_csv(output_dir/"imdb_movie_actor_master.csv")
master["primaryTitle"] = master["primaryTitle"].str.strip()

In [44]:
investment_master = master.merge(
    ml_movies[[
        "primaryTitle",
        "startYear",
        "watch_count",
        "avg_user_rating"
    ]],
    on = ["primaryTitle","startYear"],
    how="left"
)
print("Investment master shape:",investment_master.shape)

Investment master shape: (7920568, 22)

In [46]:
investment_master.to_csv(
    output_dir / "investment_mastert_dataset.csv",
    index = False
)

print("Investment master dataset saved.")

Investment master dataset saved.

In [47]:
investment_master["watch_count"].notna().sum()

881860

In [48]:
investment_master["watch_count"].isna().sum()

7038708

In [49]:
investment_master.head()

,tconst,nconst,ordering,category,job,characters,primaryTitle,originalTitle,startYear,runtimeMinutes,...,actor_name,birthYear,deathYear,primaryProfession,knownForTitles,averageRating,numVotes,avaerageRating,watch_count,avg_user_rating
0,tt0000009,nm0063086,1,actress,NaN,"[""Miss Geraldine Holbrook (Miss Jerry)""]",Miss Jerry,Miss Jerry,1894.0,45.0,...,Blanche Bayliss,1878.0,1951.0,actress,tt0000009,5.3,234.0,5.3,NaN,NaN
1,tt0000009,nm0183823,2,actor,NaN,"[""Mr. Hamilton""]",Miss Jerry,Miss Jerry,1894.0,45.0,...,William Courtenay,1875.0,1933.0,actor,"tt0000009,tt0020355,tt0021535,tt0020403",5.3,234.0,5.3,NaN,NaN
2,tt0000009,nm1309758,3,actor,NaN,"[""Chauncey Depew - the Director of the New Yor...",Miss Jerry,Miss Jerry,1894.0,45.0,...,Chauncey Depew,1834.0,1928.0,"actor,writer","tt0000009,tt0490842,tt1076833,tt4484306",5.3,234.0,5.3,NaN,NaN
3,tt0000009,nm0085156,4,director,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,...,Alexander Black,1859.0,1940.0,"director,writer,cinematographer",tt0000009,5.3,234.0,5.3,NaN,NaN
4,tt0000009,nm0085156,5,writer,NaN,NaN,Miss Jerry,Miss Jerry,1894.0,45.0,...,Alexander Black,1859.0,1940.0,"director,writer,cinematographer",tt0000009,5.3,234.0,5.3,NaN,NaN

In [108]:
investment_master["role_weight"] = 1 / investment_master["ordering"]

In [109]:
investment_master.columns

Index(['tconst', 'nconst', 'ordering', 'category', 'job', 'characters',
       'primaryTitle', 'originalTitle', 'startYear', 'runtimeMinutes',
       'genres', 'isAdult', 'actor_name', 'birthYear', 'deathYear',
       'primaryProfession', 'knownForTitles', 'averageRating', 'numVotes',
       'avaerageRating', 'watch_count', 'avg_user_rating', 'role_weight'],
      dtype='object')

In [112]:
investment_master["weighted_watch_count"] = (
    investment_master["watch_count"] * investment_master["role_weight"]
)

In [162]:
investment_master["weighted_votes"] = (
    investment_master["numVotes"] * investment_master["role_weight"]
)

In [164]:
actor_features = investment_master.groupby("actor_name").agg(
    actor_movie_count=("tconst","count"),
    actor_avg_imdb_rating=("averageRating","mean"),
    actor_weighted_votes=("weighted_votes","sum"),
    actor_total_watch_count=("weighted_watch_count","sum"),
    actor_total_votes=("numVotes","sum"),
    actor_avg_watch_count=("watch_count","mean")
).reset_index()

actor_features.head()

,actor_name,actor_movie_count,actor_avg_imdb_rating,actor_weighted_votes,actor_total_watch_count,actor_total_votes,actor_avg_watch_count
0,!'aru Ikhuisi Piet Berendse,1,7.3,19.0,0.0,76.0,NaN
1,!Nqate Xqamxebe,1,7.7,20.0,0.0,60.0,NaN
2,$2 Tony,1,5.4,6.2,0.0,62.0,NaN
3,$Minty$,1,NaN,0.0,0.0,0.0,NaN
4,$hutter,1,NaN,0.0,0.0,0.0,NaN

In [116]:
actor_features["actor_total_votes"].sort_values(ascending=False)

1060248    1.829893e+07
1804761    1.809929e+07
245110     1.647879e+07
1539973    1.537570e+07
334253     1.515756e+07
               ...
145124     0.000000e+00
145123     0.000000e+00
1014121    0.000000e+00
327315     0.000000e+00
505141     0.000000e+00
Name: actor_total_votes, Length: 1958233, dtype: float64

In [52]:
actor_features["actor_avg_imdb_rating"].sort_values(ascending=False)

1366346    10.0
1944504    10.0
1849253    10.0
321945     10.0
1624043    10.0
           ...
2050462     NaN
2050469     NaN
2050470     NaN
2050472     NaN
2050473     NaN
Name: actor_avg_imdb_rating, Length: 2050478, dtype: float64

In [117]:
actor_features["actor_movie_count"].sort_values(ascending=False)

673042     1958
807913     1354
246302     1131
739423     1057
1675141    1041
           ...
960241        1
960240        1
960238        1
960237        1
0             1
Name: actor_movie_count, Length: 1958233, dtype: int64

In [118]:
actor_features.shape

(1958233, 6)

In [119]:
actor_features.to_csv(
    output_dir / "actor_features.csv",
    index = False
)
print("Actor feature dataset created.")

Actor feature dataset created.

In [122]:
career_features = investment_master.groupby("actor_name").agg(
    career_start_year = ("startYear","min"),
    career_latest_year = ("startYear","max")
).reset_index()

career_features["career_length"] = (
    career_features["career_latest_year"] - career_features["career_start_year"]
)
career_features.head()

,actor_name,career_start_year,career_latest_year,career_length
0,!'aru Ikhuisi Piet Berendse,2014.0,2014.0,0.0
1,!Nqate Xqamxebe,2000.0,2000.0,0.0
2,$2 Tony,2010.0,2010.0,0.0
3,$Minty$,2025.0,2025.0,0.0
4,$hutter,2017.0,2017.0,0.0

In [123]:
career_features["career_length"].sort_values(ascending=False)

1129871    75.0
1412299    75.0
36610      75.0
414916     75.0
691577     75.0
           ...
953123      0.0
222022      0.0
953120      0.0
222023      0.0
0           0.0
Name: career_length, Length: 1958233, dtype: float64

In [124]:
career_features.sort_values("career_length", ascending=False).head(20)

,actor_name,career_start_year,career_latest_year,career_length
1129871,Majeed,1950.0,2025.0,75.0
1412299,Patricia Medina,1950.0,2025.0,75.0
36610,Akiko Kikuchi,1950.0,2025.0,75.0
414916,David,1950.0,2025.0,75.0
691577,Harry Lewis,1950.0,2025.0,75.0
1456331,Pilar Gómez,1950.0,2025.0,75.0
1586562,S. Ramanathan,1950.0,2025.0,75.0
1805801,Tom Neal,1950.0,2025.0,75.0
314968,Charlton Heston,1950.0,2025.0,75.0
870805,John Archer,1950.0,2025.0,75.0
1442713,Peter Sullivan,1950.0,2025.0,75.0
1067735,Liam O'Leary,1950.0,2025.0,75.0
784652,James Anderson,1950.0,2025.0,75.0
416013,David Bauer,1950.0,2025.0,75.0
1463444,Pran Sikand,1950.0,2025.0,75.0
787176,James Griffith,1950.0,2025.0,75.0
567754,Federico Fellini,1950.0,2025.0,75.0
193758,Balam,1950.0,2025.0,75.0
1544201,Robert Ryan,1950.0,2025.0,75.0
1566102,Rosalind Russell,1950.0,2025.0,75.0

In [125]:
investment_master = investment_master[
    (investment_master["startYear"] >= 1950) &
    (investment_master["startYear"] <= 2025)
]

In [126]:
investment_master.shape

(7086498, 25)

In [127]:
career_features = investment_master.groupby("actor_name").agg(
    career_start_year=("startYear", "min"),
    career_latest_year=("startYear", "max")
).reset_index()

career_features["career_length"] = (
    career_features["career_latest_year"]
    - career_features["career_start_year"]
)

In [128]:
career_features["career_length"].describe()

count    1.958233e+06
mean     4.822784e+00
std      1.031770e+01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      5.000000e+00
max      7.500000e+01
Name: career_length, dtype: float64

In [129]:
career_features["career_length"].sort_values(ascending=False)

1129871    75.0
1412299    75.0
36610      75.0
414916     75.0
691577     75.0
           ...
953123      0.0
222022      0.0
953120      0.0
222023      0.0
0           0.0
Name: career_length, Length: 1958233, dtype: float64

In [131]:
actor_features = actor_features.merge(
    career_features,
    on="actor_name",
    how="left"
)

In [167]:
actor_features.columns

Index(['actor_name', 'actor_movie_count', 'actor_avg_imdb_rating',
       'actor_weighted_votes', 'actor_total_watch_count', 'actor_total_votes',
       'actor_avg_watch_count'],
      dtype='object')

In [68]:
career_features.columns

Index(['actor_name', 'career_start_year', 'career_latest_year',
       'career_length'],
      dtype='object')

In [168]:
actor_features = actor_features.merge(
    career_features,
    on="actor_name",
    how="left"
)

actor_features.head()

,actor_name,actor_movie_count,actor_avg_imdb_rating,actor_weighted_votes,actor_total_watch_count,actor_total_votes,actor_avg_watch_count,career_start_year,career_latest_year,career_length
0,!'aru Ikhuisi Piet Berendse,1,7.3,19.0,0.0,76.0,NaN,2014.0,2014.0,0.0
1,!Nqate Xqamxebe,1,7.7,20.0,0.0,60.0,NaN,2000.0,2000.0,0.0
2,$2 Tony,1,5.4,6.2,0.0,62.0,NaN,2010.0,2010.0,0.0
3,$Minty$,1,NaN,0.0,0.0,0.0,NaN,2025.0,2025.0,0.0
4,$hutter,1,NaN,0.0,0.0,0.0,NaN,2017.0,2017.0,0.0

In [169]:
actor_features.to_csv(
    output_dir / "actor_features.csv",
    index=False
)
print("Actor feature update and save.")

Actor feature update and save.

In [134]:
actor_features = actor_features[
    (actor_features["actor_movie_count"] >= 3) & (actor_features["career_length"] >= 2)
]

actor_features.shape

(473843, 9)

In [165]:
actor_features.to_csv(
    output_dir / "actor_features_cleaned.csv",
    index = False
)

print("Cleaned actor feature saved.")

Cleaned actor feature saved.

In [166]:
actor_features.columns

Index(['actor_name', 'actor_movie_count', 'actor_avg_imdb_rating',
       'actor_weighted_votes', 'actor_total_watch_count', 'actor_total_votes',
       'actor_avg_watch_count'],
      dtype='object')

In [174]:
current_year = 2025
actor_features["recency_score"] = (
    1/(current_year - actor_features["career_latest_year"] + 1)
)

In [175]:
actor_features.columns

Index(['actor_name', 'actor_movie_count', 'actor_avg_imdb_rating',
       'actor_weighted_votes', 'actor_total_watch_count', 'actor_total_votes',
       'actor_avg_watch_count', 'career_start_year', 'career_latest_year',
       'career_length', 'norm_movie_count', 'norm_weighted_votes',
       'norm_weighted_watch', 'norm_career_length', 'norm_rating',
       'recency_score'],
      dtype='object')

In [171]:
import numpy as np

actor_features["norm_movie_count"] = np.log1p(actor_features["actor_movie_count"])
actor_features["norm_weighted_votes"] = np.log1p(actor_features["actor_weighted_votes"])
actor_features["norm_weighted_watch"] = np.log1p(actor_features["actor_total_watch_count"])
actor_features["norm_career_length"] = actor_features["career_length"]
actor_features["norm_rating"] = actor_features["actor_avg_imdb_rating"]

In [176]:
actor_features["actor_investment_score"] = (
    
    0.30 * actor_features["norm_weighted_watch"] +
    0.25 * actor_features["norm_weighted_votes"] +
    0.20 * actor_features["norm_rating"] +
    0.15 * actor_features["recency_score"] +
    0.10 * actor_features["norm_movie_count"]

)

In [177]:
actor_features= actor_features.sort_values(
    "actor_investment_score",
    ascending=False
)

actor_features.head(20)

,actor_name,actor_movie_count,actor_avg_imdb_rating,actor_weighted_votes,actor_total_watch_count,actor_total_votes,actor_avg_watch_count,career_start_year,career_latest_year,career_length,norm_movie_count,norm_weighted_votes,norm_weighted_watch,norm_career_length,norm_rating,recency_score,actor_investment_score
1804761,Tom Hanks,100,6.772000,1.809929e+07,630266.665867,21966581.0,10729.550725,1980.0,2024.0,44.0,4.615121,16.711383,13.353900,44.0,6.772000,0.500000,10.074928
245110,Brad Pitt,81,6.937975,1.647879e+07,323293.933275,26799436.0,10016.340426,1988.0,2025.0,37.0,4.406719,16.617585,12.686320,37.0,6.937975,1.000000,9.938559
1803986,Tom Cruise,80,6.900000,1.368042e+07,382267.622538,19793155.0,9916.132075,1981.0,2025.0,44.0,4.394449,16.431477,12.853879,44.0,6.900000,1.000000,9.933478
1060248,Leonardo DiCaprio,68,7.046154,1.829893e+07,261955.609045,22463728.0,8187.108108,1991.0,2025.0,34.0,4.234107,16.722353,12.475934,34.0,7.046154,1.000000,9.906010
690610,Harrison Ford,76,6.878873,9.878075e+06,419020.104762,14548878.0,13643.454545,1967.0,2025.0,58.0,4.343805,16.105828,12.945677,58.0,6.878873,1.000000,9.870315
882552,Johnny Depp,101,6.855000,1.180434e+07,330832.888332,14396382.0,6499.350877,1984.0,2025.0,41.0,4.624973,16.283978,12.709372,41.0,6.855000,1.000000,9.867303
1539759,Robert De Niro,146,6.564085,1.252912e+07,303425.865629,20138528.0,5161.958333,1968.0,2025.0,57.0,4.990433,16.343566,12.622896,57.0,6.564085,1.000000,9.834620
1231887,Mel Gibson,89,6.442857,6.225081e+06,331472.139448,11517213.0,9029.872727,1977.0,2025.0,48.0,4.499810,15.644097,12.711302,48.0,6.442857,1.000000,9.612967
849305,Jim Carrey,57,6.673214,8.731627e+06,241515.597409,11486225.0,13117.000000,1985.0,2025.0,40.0,4.060443,15.982462,12.394693,40.0,6.673214,1.000000,9.604711
1208172,Matt Damon,91,6.903333,1.065980e+07,182993.762207,18338486.0,7639.576923,1992.0,2024.0,32.0,4.521789,16.181991,12.117213,32.0,6.903333,0.500000,9.588507
1539973,Robert Downey Jr.,83,6.598765,1.537570e+07,172670.579834,22869209.0,4631.925926,1975.0,2023.0,48.0,4.430817,16.548299,12.059147,48.0,6.598765,0.333333,9.567654
162975,Arnold Schwarzenegger,68,6.264516,7.347545e+06,303477.566667,8541435.0,8258.000000,1966.0,2025.0,59.0,4.234107,15.809877,12.623066,59.0,6.264516,1.000000,9.565703
334253,Christian Bale,56,6.912500,1.515756e+07,156714.350183,18131508.0,6027.694444,1987.0,2023.0,36.0,4.043051,16.534010,11.962186,36.0,6.912500,0.333333,9.558964
1549394,Robin Williams,81,6.542105,6.041520e+06,327847.737302,9867429.0,8903.224138,1976.0,2024.0,48.0,4.406719,15.614166,12.700308,48.0,6.542105,0.500000,9.537727
725265,Hugh Jackman,61,6.818966,9.733086e+06,155773.547059,16996505.0,7909.461538,1999.0,2025.0,26.0,4.127134,16.091042,11.956165,26.0,6.818966,1.000000,9.536116
975184,Keanu Reeves,82,6.595122,9.780842e+06,156466.733333,11472134.0,4130.191489,1986.0,2025.0,39.0,4.418841,16.095936,11.960605,39.0,6.595122,1.000000,9.523074
207111,Ben Affleck,90,6.501136,8.596098e+06,178078.665493,16805396.0,6419.072727,1992.0,2025.0,33.0,4.510860,15.966819,12.089986,33.0,6.501136,1.000000,9.520014
1349532,Nicolas Cage,147,5.921918,8.041511e+06,210199.925678,11701257.0,2849.438776,1983.0,2025.0,42.0,4.997212,15.900128,12.255819,42.0,5.921918,1.000000,9.485882
1067714,Liam Neeson,106,6.386538,7.253149e+06,186078.613095,11662874.0,5368.203704,1978.0,2025.0,47.0,4.672829,15.796946,12.133930,47.0,6.386538,1.000000,9.484006
39199,Al Pacino,70,6.664286,8.379636e+06,154442.496515,10768393.0,4252.954545,1971.0,2025.0,54.0,4.262680,15.941315,11.947584,54.0,6.664286,1.000000,9.478729

In [142]:
actor_features.to_csv(
    output_dir / "actor_investment_ranking.csv",
    index=False
)
print("Actor investment ranking created.")

Actor investment ranking created.

In [143]:
genre_data = investment_master.copy()

In [144]:
genre_data["genres"] = genre_data["genres"].fillna("Unknown")

genre_data = genre_data.assign(
    genre = genre_data["genres"].str.split(",")
)

genre_data = genre_data.explode("genre")
genre_data.head()

,tconst,nconst,ordering,category,job,characters,primaryTitle,originalTitle,startYear,runtimeMinutes,...,knownForTitles,averageRating,numVotes,avaerageRating,watch_count,avg_user_rating,role_weight,weighted_watch_count,weight_votes,genre
59487,tt0011801,nm0681726,1,actor,NaN,"[""Musiker Erik Paulsen""]",Tötet nicht mehr,Tötet nicht mehr,2019.0,NaN,...,"tt0017248,tt0011780,tt0009296,tt0439040",NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,Action
59487,tt0011801,nm0681726,1,actor,NaN,"[""Musiker Erik Paulsen""]",Tötet nicht mehr,Tötet nicht mehr,2019.0,NaN,...,"tt0017248,tt0011780,tt0009296,tt0439040",NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,Crime
59488,tt0011801,nm0692612,2,actress,NaN,"[""Karin, Tochter Brückner""]",Tötet nicht mehr,Tötet nicht mehr,2019.0,NaN,...,"tt0459172,tt0013809,tt0012235,tt0154741",NaN,NaN,NaN,NaN,NaN,0.500000,NaN,NaN,Action
59488,tt0011801,nm0692612,2,actress,NaN,"[""Karin, Tochter Brückner""]",Tötet nicht mehr,Tötet nicht mehr,2019.0,NaN,...,"tt0459172,tt0013809,tt0012235,tt0154741",NaN,NaN,NaN,NaN,NaN,0.500000,NaN,NaN,Crime
59489,tt0011801,nm0726256,3,actor,NaN,"[""Sebald, Sohn Brückner""]",Tötet nicht mehr,Tötet nicht mehr,2019.0,NaN,...,"tt0027319,tt0025292,tt0022071,tt0027846",NaN,NaN,NaN,NaN,NaN,0.333333,NaN,NaN,Action

In [145]:
genre_features = genre_data.groupby("genre").agg(
    genre_movie_count=("tconst","nunique"),
    genre_avg_imdb_rating=("averageRating","mean"),
    genre_total_votes=("numVotes","sum"),
    genre_total_watch_count=("watch_count","sum"),
    genre_avg_watch_count=("watch_count","mean")
).reset_index()

genre_features.head()

,genre,genre_movie_count,genre_avg_imdb_rating,genre_total_votes,genre_total_watch_count,genre_avg_watch_count
0,Action,45436,5.721380,9.195274e+09,157879693.0,1202.755441
1,Adult,8620,5.617715,4.800199e+06,5724.0,12.283262
2,Adventure,23128,5.861579,7.633355e+09,156397946.0,1944.208272
3,Animation,8421,6.325652,1.776789e+09,33970946.0,1347.732524
4,Biography,15910,6.881442,1.775748e+09,30348682.0,708.717061

In [146]:
genre_features.shape

(29, 6)

In [147]:
genre_features["norm_movie_count"] = np.log1p(genre_features["genre_movie_count"])
genre_features["norm_votes"] = np.log1p(genre_features["genre_total_votes"])
genre_features["norm_watch_count"] = np.log1p(genre_features["genre_total_watch_count"])
genre_features["norm_rating"] = genre_features["genre_avg_imdb_rating"]

In [148]:
genre_features.shape

(29, 10)

In [149]:
genre_features["genre_investment_score"] = (
    0.30 * genre_features["norm_watch_count"] +
    0.25 * genre_features["norm_votes"] +
    0.25 * genre_features["norm_movie_count"] +
    0.20 * genre_features["norm_rating"]
)

In [150]:
genre_features.head()

,genre,genre_movie_count,genre_avg_imdb_rating,genre_total_votes,genre_total_watch_count,genre_avg_watch_count,norm_movie_count,norm_votes,norm_watch_count,norm_rating,genre_investment_score
0,Action,45436,5.721380,9.195274e+09,157879693.0,1202.755441,10.724082,22.941956,18.877344,5.721380,15.223989
1,Adult,8620,5.617715,4.800199e+06,5724.0,12.283262,9.061956,15.384168,8.652598,5.617715,9.830853
2,Adventure,23128,5.861579,7.633355e+09,156397946.0,1944.208272,10.048843,22.755793,18.867914,5.861579,15.033849
3,Animation,8421,6.325652,1.776789e+09,33970946.0,1347.732524,9.038603,21.298074,17.341016,6.325652,14.051604
4,Biography,15910,6.881442,1.775748e+09,30348682.0,708.717061,9.674766,21.297487,17.228264,6.881442,14.287831

In [91]:
genre_features = genre_features.sort_values(
    "genre_investment_score",
    ascending=False
)

genre_features.head(20)

,genre,genre_movie_count,genre_avg_imdb_rating,genre_total_votes,genre_total_watch_count,genre_avg_watch_count,norm_movie_count,norm_votes,norm_watch_count,norm_rating,genre_investment_score
8,Drama,200092,6.214924,1.351916e+10,232411843.0,531.323011,12.206538,23.327374,19.264022,6.214924,15.905669
5,Comedy,94791,5.859550,8.181468e+09,185742157.0,712.614117,11.459440,22.825137,19.039870,5.859550,15.455015
0,Action,45436,5.721380,9.195274e+09,157879693.0,1202.755441,10.724082,22.941956,18.877344,5.721380,15.223989
2,Adventure,23128,5.861579,7.633355e+09,156397946.0,1944.208272,10.048843,22.755793,18.867914,5.861579,15.033849
6,Crime,32482,5.959996,5.219886e+09,91293842.0,765.695228,10.388472,22.375741,18.329594,5.959996,14.881931
20,Romance,41023,6.070726,3.090799e+09,70036011.0,605.444565,10.621913,21.851695,18.064520,6.070726,14.751903
25,Thriller,35587,5.568001,4.604589e+09,77301279.0,658.432386,10.479764,22.250319,18.163221,5.568001,14.745087
21,Sci-Fi,10074,5.304101,3.573771e+09,75855548.0,1816.638280,9.217812,21.996887,18.144341,5.304101,14.307797
4,Biography,15910,6.881442,1.775748e+09,30348682.0,708.717061,9.674766,21.297487,17.228264,6.881442,14.287831
10,Fantasy,13369,5.805100,2.664114e+09,49758740.0,1176.830330,9.500769,21.703138,17.722697,5.805100,14.278806
17,Mystery,15329,5.765541,2.824319e+09,41695888.0,652.998105,9.637567,21.761533,17.545913,5.765541,14.266657
14,Horror,31953,4.951754,2.788923e+09,31661345.0,300.629006,10.372053,21.748921,17.270607,4.951754,14.201776
3,Animation,8421,6.325652,1.776789e+09,33970946.0,1347.732524,9.038603,21.298074,17.341016,6.325652,14.051604
9,Family,16687,6.108346,1.181132e+09,27145822.0,757.797499,9.722445,20.889739,17.116734,6.108346,14.009735
7,Documentary,129527,7.200367,3.038249e+08,5493702.0,72.640151,11.771652,19.531962,15.519113,7.200367,13.921711
13,History,13314,6.747229,7.647430e+08,13501473.0,462.965847,9.496646,20.455050,16.418309,6.747229,13.762863
15,Music,13160,6.736846,5.376724e+08,11698213.0,445.646210,9.485013,20.102760,16.274947,6.736846,13.626797
27,War,7401,6.361175,5.539615e+08,11817034.0,666.011047,8.909506,20.132606,16.285053,6.361175,13.418279
23,Sport,6744,6.573136,4.527192e+08,8423518.0,507.288046,8.816557,19.930783,15.946538,6.573136,13.285423
16,Musical,8128,6.178849,2.471995e+08,4603618.0,374.979067,9.003193,19.325706,15.342353,6.178849,12.920701

In [151]:
genre_features.to_csv(
    output_dir / "genre_investment_rankings.csv",
    index = False
)

print("Genre investment rankings created.")

Genre investment rankings created.

In [152]:
genre_features.shape

(29, 11)

In [178]:
actor_features.columns

Index(['actor_name', 'actor_movie_count', 'actor_avg_imdb_rating',
       'actor_weighted_votes', 'actor_total_watch_count', 'actor_total_votes',
       'actor_avg_watch_count', 'career_start_year', 'career_latest_year',
       'career_length', 'norm_movie_count', 'norm_weighted_votes',
       'norm_weighted_watch', 'norm_career_length', 'norm_rating',
       'recency_score', 'actor_investment_score'],
      dtype='object')

In [179]:
actor_death = investment_master.groupby("actor_name").agg(
    deathYear=("deathYear","first")
).reset_index()

actor_death.head()

                    actor_name  deathYear
0  !'aru Ikhuisi Piet Berendse        NaN
1              !Nqate Xqamxebe        NaN
2                      $2 Tony        NaN
3                      $Minty$        NaN
4                      $hutter        NaN

In [180]:
actor_features = actor_features.merge(
    actor_death,
    on = "actor_name",
    how = "left"
)

In [181]:
actor_features["is_alive"] = actor_features["deathYear"].isna().astype(int)

In [182]:
actor_features.sort_values("is_alive",ascending=False).head(20)

,actor_name,actor_movie_count,actor_avg_imdb_rating,actor_weighted_votes,actor_total_watch_count,actor_total_votes,actor_avg_watch_count,career_start_year,career_latest_year,career_length,norm_movie_count,norm_weighted_votes,norm_weighted_watch,norm_career_length,norm_rating,recency_score,actor_investment_score,deathYear,is_alive
0,Tom Hanks,100,6.772,1.809929e+07,630266.665867,21966581.0,10729.550725,1980.0,2024.0,44.0,4.615121,16.711383,13.353900,44.0,6.772,0.500000,10.074928,NaN,1
1301919,Reza Gheblei,1,4.600,6.333333e+00,0.000000,57.0,NaN,1986.0,1986.0,0.0,0.693147,1.992430,0.000000,0.0,4.600,0.025000,1.491172,NaN,1
1301931,Hasan Karabacak,1,6.000,1.333333e+00,0.000000,8.0,NaN,2011.0,2011.0,0.0,0.693147,0.847298,0.000000,0.0,6.000,0.066667,1.491139,NaN,1
1301930,Austin German,1,6.000,1.333333e+00,0.000000,8.0,NaN,2011.0,2011.0,0.0,0.693147,0.847298,0.000000,0.0,6.000,0.066667,1.491139,NaN,1
1301929,Mike Vanderhoof,1,6.000,1.333333e+00,0.000000,12.0,NaN,2011.0,2011.0,0.0,0.693147,0.847298,0.000000,0.0,6.000,0.066667,1.491139,NaN,1
1301928,Arif Guler,1,6.000,1.333333e+00,0.000000,12.0,NaN,2011.0,2011.0,0.0,0.693147,0.847298,0.000000,0.0,6.000,0.066667,1.491139,NaN,1
1301927,Amirmasoud Vaez Tehrani,1,5.900,1.333333e+00,0.000000,12.0,NaN,2021.0,2021.0,0.0,0.693147,0.847298,0.000000,0.0,5.900,0.200000,1.491139,NaN,1
1301926,Angela Amante,1,4.000,9.428571e+00,0.071429,132.0,1.000000,2016.0,2016.0,0.0,0.693147,2.344549,0.068993,0.0,4.000,0.100000,1.491150,NaN,1
1301925,Lee Fenton-Wilkinson,1,5.800,1.684211e+00,0.000000,32.0,NaN,2016.0,2016.0,0.0,0.693147,0.987387,0.000000,0.0,5.800,0.100000,1.491161,NaN,1
1301924,José Santa Clara,4,5.200,1.888889e+00,0.000000,16.0,NaN,2018.0,2020.0,2.0,1.609438,1.060872,0.000000,2.0,5.200,0.166667,1.491162,NaN,1
1301923,Amir Rezaie,6,4.000,3.000000e+00,0.000000,9.0,NaN,2020.0,2025.0,5.0,1.945910,1.386294,0.000000,5.0,4.000,1.000000,1.491165,NaN,1
1301922,Chuks Obaze,2,5.100,2.473684e+00,0.000000,47.0,NaN,2018.0,2023.0,5.0,1.098612,1.245216,0.000000,5.0,5.100,0.333333,1.491165,NaN,1
1301921,Emeka Nwaeme,1,4.700,5.428571e+00,0.000000,38.0,NaN,2017.0,2017.0,0.0,0.693147,1.860752,0.000000,0.0,4.700,0.111111,1.491169,NaN,1
1301920,Joseph L. Callaway,1,4.700,5.428571e+00,0.000000,76.0,NaN,2017.0,2017.0,0.0,0.693147,1.860752,0.000000,0.0,4.700,0.111111,1.491169,NaN,1
1301918,Rory Maclean,1,4.600,6.333333e+00,0.000000,76.0,NaN,1986.0,1986.0,0.0,0.693147,1.992430,0.000000,0.0,4.600,0.025000,1.491172,NaN,1
1301904,Ali Kemal Aydin,1,4.600,5.833333e+00,0.000000,35.0,NaN,2019.0,2019.0,0.0,0.693147,1.921813,0.000000,0.0,4.600,0.142857,1.491196,NaN,1
1301917,Olavi Metsistö,2,5.300,2.566667e+00,0.000000,14.0,NaN,1982.0,1982.0,0.0,1.098612,1.271631,0.000000,0.0,5.300,0.022727,1.491178,NaN,1
1301916,Zack Varkaris,1,6.000,1.300000e+00,0.000000,13.0,NaN,2015.0,2015.0,0.0,0.693147,0.832909,0.000000,0.0,6.000,0.090909,1.491178,NaN,1
1301915,Jan Czernik,1,6.000,1.300000e+00,0.000000,13.0,NaN,2015.0,2015.0,0.0,0.693147,0.832909,0.000000,0.0,6.000,0.090909,1.491178,NaN,1
1301914,George Duncombe Jr.,1,6.000,1.300000e+00,0.000000,13.0,NaN,2015.0,2015.0,0.0,0.693147,0.832909,0.000000,0.0,6.000,0.090909,1.491178,NaN,1

In [183]:
actor_features["future_investment_score"] = (
    actor_features["actor_investment_score"] * actor_features["is_alive"]
)

In [184]:
actor_features.sort_values("future_investment_score",ascending=False).head()

,actor_name,actor_movie_count,actor_avg_imdb_rating,actor_weighted_votes,actor_total_watch_count,actor_total_votes,actor_avg_watch_count,career_start_year,career_latest_year,career_length,norm_movie_count,norm_weighted_votes,norm_weighted_watch,norm_career_length,norm_rating,recency_score,actor_investment_score,deathYear,is_alive,future_investment_score
0,Tom Hanks,100,6.772000,1.809929e+07,630266.665867,21966581.0,10729.550725,1980.0,2024.0,44.0,4.615121,16.711383,13.353900,44.0,6.772000,0.5,10.074928,NaN,1,10.074928
1,Brad Pitt,81,6.937975,1.647879e+07,323293.933275,26799436.0,10016.340426,1988.0,2025.0,37.0,4.406719,16.617585,12.686320,37.0,6.937975,1.0,9.938559,NaN,1,9.938559
2,Tom Cruise,80,6.900000,1.368042e+07,382267.622538,19793155.0,9916.132075,1981.0,2025.0,44.0,4.394449,16.431477,12.853879,44.0,6.900000,1.0,9.933478,NaN,1,9.933478
3,Leonardo DiCaprio,68,7.046154,1.829893e+07,261955.609045,22463728.0,8187.108108,1991.0,2025.0,34.0,4.234107,16.722353,12.475934,34.0,7.046154,1.0,9.906010,NaN,1,9.906010
4,Harrison Ford,76,6.878873,9.878075e+06,419020.104762,14548878.0,13643.454545,1967.0,2025.0,58.0,4.343805,16.105828,12.945677,58.0,6.878873,1.0,9.870315,NaN,1,9.870315

In [185]:
actor_features.columns

Index(['actor_name', 'actor_movie_count', 'actor_avg_imdb_rating',
       'actor_weighted_votes', 'actor_total_watch_count', 'actor_total_votes',
       'actor_avg_watch_count', 'career_start_year', 'career_latest_year',
       'career_length', 'norm_movie_count', 'norm_weighted_votes',
       'norm_weighted_watch', 'norm_career_length', 'norm_rating',
       'recency_score', 'actor_investment_score', 'deathYear', 'is_alive',
       'future_investment_score'],
      dtype='object')

In [186]:
actor_features.to_csv(
    output_dir / "actor_investment_ranking.csv",
    index=False
)
print("Actor investment ranking created.")

Actor investment ranking created.

In [188]:
future_actors = actor_features[
actor_features["is_alive"] == 1
].sort_values("future_investment_score",ascending=False)

In [189]:
actor_features.to_csv(
    "../data/processed/actor_features_final.csv",
    index=False
)

future_actors.to_csv(
    "../data/processed/future_actor_investment_rankings.csv",
    index=False
)

In [191]:
future_actors.head(10)

,actor_name,actor_movie_count,actor_avg_imdb_rating,actor_weighted_votes,actor_total_watch_count,actor_total_votes,actor_avg_watch_count,career_start_year,career_latest_year,career_length,norm_movie_count,norm_weighted_votes,norm_weighted_watch,norm_career_length,norm_rating,recency_score,actor_investment_score,deathYear,is_alive,future_investment_score
0,Tom Hanks,100,6.772000,1.809929e+07,630266.665867,21966581.0,10729.550725,1980.0,2024.0,44.0,4.615121,16.711383,13.353900,44.0,6.772000,0.5,10.074928,NaN,1,10.074928
1,Brad Pitt,81,6.937975,1.647879e+07,323293.933275,26799436.0,10016.340426,1988.0,2025.0,37.0,4.406719,16.617585,12.686320,37.0,6.937975,1.0,9.938559,NaN,1,9.938559
2,Tom Cruise,80,6.900000,1.368042e+07,382267.622538,19793155.0,9916.132075,1981.0,2025.0,44.0,4.394449,16.431477,12.853879,44.0,6.900000,1.0,9.933478,NaN,1,9.933478
3,Leonardo DiCaprio,68,7.046154,1.829893e+07,261955.609045,22463728.0,8187.108108,1991.0,2025.0,34.0,4.234107,16.722353,12.475934,34.0,7.046154,1.0,9.906010,NaN,1,9.906010
4,Harrison Ford,76,6.878873,9.878075e+06,419020.104762,14548878.0,13643.454545,1967.0,2025.0,58.0,4.343805,16.105828,12.945677,58.0,6.878873,1.0,9.870315,NaN,1,9.870315
5,Johnny Depp,101,6.855000,1.180434e+07,330832.888332,14396382.0,6499.350877,1984.0,2025.0,41.0,4.624973,16.283978,12.709372,41.0,6.855000,1.0,9.867303,NaN,1,9.867303
6,Robert De Niro,146,6.564085,1.252912e+07,303425.865629,20138528.0,5161.958333,1968.0,2025.0,57.0,4.990433,16.343566,12.622896,57.0,6.564085,1.0,9.834620,NaN,1,9.834620
7,Mel Gibson,89,6.442857,6.225081e+06,331472.139448,11517213.0,9029.872727,1977.0,2025.0,48.0,4.499810,15.644097,12.711302,48.0,6.442857,1.0,9.612967,NaN,1,9.612967
8,Jim Carrey,57,6.673214,8.731627e+06,241515.597409,11486225.0,13117.000000,1985.0,2025.0,40.0,4.060443,15.982462,12.394693,40.0,6.673214,1.0,9.604711,NaN,1,9.604711
9,Matt Damon,91,6.903333,1.065980e+07,182993.762207,18338486.0,7639.576923,1992.0,2024.0,32.0,4.521789,16.181991,12.117213,32.0,6.903333,0.5,9.588507,NaN,1,9.588507